In [45]:
import pandas as pd 
df = pd.read_csv("train.csv")
df.head()
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 472 entries, 0 to 471
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Loan_ID            472 non-null    object
 1   Gender             464 non-null    object
 2   Married            469 non-null    object
 3   Dependents         461 non-null    object
 4   Education          472 non-null    object
 5   Self_Employed      446 non-null    object
 6   ApplicantIncome    472 non-null    int64
 7   CoapplicantIncome  472 non-null    float64
 8   LoanAmount         458 non-null    float64
 9   Loan_Amount_Term   461 non-null    float64
 10  Credit_History     429 non-null    float64
 11  Property_Area      472 non-null    object
 12  Loan_Status        472 non-null    object
dtypes: float64(4), int64(1), object(8)
memory usage: 48.1+ KB

,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History
count,472.000000,472.000000,458.000000,461.000000,429.000000
mean,5562.283898,1487.771017,145.628821,341.180043,0.946387
std,6580.578703,1934.875373,87.660461,62.851621,0.225516
min,210.000000,0.000000,17.000000,12.000000,0.000000
25%,2917.000000,0.000000,100.000000,360.000000,1.000000
50%,3858.500000,1128.500000,126.000000,360.000000,1.000000
75%,5823.000000,2287.750000,162.000000,360.000000,1.000000
max,81000.000000,20000.000000,700.000000,480.000000,1.000000

In [46]:
df.isnull().sum()

Loan_ID               0
Gender                8
Married               3
Dependents           11
Education             0
Self_Employed        26
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           14
Loan_Amount_Term     11
Credit_History       43
Property_Area         0
Loan_Status           0
dtype: int64

In [47]:
df["Gender"].fillna(df['Gender'].mode()[0], inplace=True)
df["Married"].fillna(df['Married'].mode()[0], inplace=True)
df["Dependents"].fillna(df['Dependents'].mode()[0], inplace=True)
df["Self_Employed"].fillna(df['Self_Employed'].mode()[0], inplace=True)
df["LoanAmount"].fillna(df['LoanAmount'].mean(), inplace=True)
df["Loan_Amount_Term"].fillna(df['Loan_Amount_Term'].mean(), inplace=True)
df["Credit_History"].fillna(1, inplace = True)

df.isnull().sum()

C:\Users\prade\AppData\Local\Temp\ipykernel_21308\4172117230.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Gender"].fillna(df['Gender'].mode()[0], inplace=True)
C:\Users\prade\AppData\Local\Temp\ipykernel_21308\4172117230.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Married"].fillna(df['Married'].mode()[0], inplace=True)
C:\Users\prade\AppData\Local\Temp\ipykernel_21308\4172117230.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Dependents"].fillna(df['Dependents'].mode()[0], inplace=True)
C:\Users\prade\AppData\Local\Temp\ipykernel_21308\4172117230.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Self_Employed"].fillna(df['Self_Employed'].mode()[0], inplace=True)
C:\Users\prade\AppData\Local\Temp\ipykernel_21308\4172117230.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["LoanAmount"].fillna(df['LoanAmount'].mean(), inplace=True)
C:\Users\prade\AppData\Local\Temp\ipykernel_21308\4172117230.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Loan_Amount_Term"].fillna(df['Loan_Amount_Term'].mean(), inplace=True)
C:\Users\prade\AppData\Local\Temp\ipykernel_21308\4172117230.py:7: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Credit_History"].fillna(1, inplace = True)

Loan_ID              0
Gender               0
Married              0
Dependents           0
Education            0
Self_Employed        0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
Credit_History       0
Property_Area        0
Loan_Status          0
dtype: int64

In [ ]:
df["Loan_Status"] = df['Loan_Status'].map({'Y':1, 'N':0})

,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,Male,Yes,0,Graduate,No,2958,2900.0,131.0,360.0,1.0,Semiurban,1
1,Female,Yes,0,Graduate,No,2929,2333.0,139.0,360.0,1.0,Semiurban,1
2,Female,No,0,Graduate,No,3086,0.0,120.0,360.0,1.0,Semiurban,1
3,Male,No,0,Graduate,No,2500,20000.0,103.0,360.0,1.0,Semiurban,1
4,Male,Yes,3+,Graduate,No,2666,2083.0,95.0,360.0,1.0,Rural,1

In [50]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

cols = ['Gender', 'Married', 'Education', 'Self_Employed', 'Property_Area', 'Dependents']

for col in cols:
    X[col]  = le.fit_transform(X[col])

In [51]:
from sklearn.model_selection import train_test_split 

X_train, X_test_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=42)

In [52]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

ValueError: could not convert string to float: 'Female'